name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - name: Tag and Push Gem
        id: tag-and-push-gem
        uses: discourse/publish-rubygems-action@04549cca4eecd343acd215114ebbbdb99630af90
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIT_EMAIL: ${{secrets.ALEX_GIT_EMAIL}}
          GIT_NAME: ${{secrets.ALEX_GIT_NAME}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
      - name: Debug "There are files that need to be committed first."
        if: always()
        run: |
          echo "test"
          echo "test 2"
          git diff
          echo "test 3"
          git diff-index --quiet --cached HEAD
          echo "test 4"
          git diff --exit-code
          echo "test 5"
          echo "$(git diff)"
          echo "test 6"
          echo "$(git diff-index --quiet --cached HEAD)"
          echo "test 7"
          echo "$(git diff --exit-code)"
          echo "test 8"
          git status
          echo "test 9"
          echo "$(git status)"
          echo "test 10"
        shell: bash {0}
      - name: Create GitHub Release
        run: gh release create v${{steps.tag-and-push-gem.outputs.gem_version}} --generate-notes
        if: ${{ steps.tag-and-push-gem.outputs.new_version == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
